### ISSUE TITLE
Add user guide

### ISSUE THREAD

**Issue by ssandhuanmol** [Smattr/clink#227]

**Comment by Smattr** [comment]
Ah, now your email makes more sense. Can you elaborate on what you’d like to see in a use guide? There’s already a man page, so I guess something beyond what is documented there?

**Comment by ssandhuanmol** [comment]
man page should be enough, just add manage to git repo similar to readme section

**Comment by ssandhuanmol** [comment]
sorry meant "man page"

**Comment by Smattr** [comment]
Ah I see. I’m still unclear what you’re requesting though, as [the man page is already in the repo](https://github.com/Smattr/clink/blob/main/clink/src/clink.1).
