### ISSUE TITLE
assertion id >= 0 failed

### ISSUE THREAD

**Issue by terminatorul** [Smattr/clink#242]
I built and tried clink, for one of my work projects, but I get the above assertion multiple times when I try to generate the database. I used 100 C source files (all *.c) listed in my namefile and in compile_commands.json, with --parse-C=clang option on the command line

**Comment by Smattr** [comment]
Can you elaborate? I don’t see that assertion anywhere in Clink’s code, so I’m not sure what failure you are seeing.

**Comment by terminatorul** [comment]
Now I only get issue https://github.com/Smattr/clink/issues/243, it appears to be blocking the real problem with the assert 

However I found the assert in the source code:
- https://github.com/Smattr/clink/blob/main/clink/src/build.c#L118
- https://github.com/Smattr/clink/blob/main/libclink/src/db_add_symbol.c#L65

**Comment by Smattr** [comment]
Oh it’s `id` with a lowercase i. I was grepping for it with uppercase as per the issue title.

**Comment by terminatorul** [comment]
Yes, sorry ! Fixed the spelling now ...

**Comment by Smattr** [comment]
I don’t think it will be much help to your goals of parsing your current code base, but I think the root cause of this one is an unchecked failure. https://github.com/Smattr/clink/pull/245
