### ISSUE TITLE
clang can not find source file in compilation database

### ISSUE THREAD

**Issue by terminatorul** [Smattr/clink#243]
Hello !

My work project has about 13000 source files in C (without the headers), and I generated a compilation database for them. I tried with absolute and relative paths, and also both formats in the compilation database (string vs array for the command line)

I built clink with latest clang 18 in openSUSE Tumbleweed.

When running clink with --parse-C=clang, , it says clang can not find the source files in the compilation database. But when I copy and search the source file name, it is right there in the .json file.

Is there a way to fix this, or is the issue directly from clang ?

Can clink also use (and document) the simpler alternative file compile_flags.txt, that can be used by clang instead of compile_commands.json ?

**Comment by terminatorul** [comment]
I have attached my compile database here: [compile_commands.json.tar.gz](https://github.com/Smattr/clink/files/15317893/compile_commands.json.tar.gz) and the namefile list here if it helps: [namefile.files.tar.gz](https://github.com/Smattr/clink/files/15318054/namefile.files.tar.gz)

You can look for the `"arguments"` field in the file format specification from clang  (https://clang.llvm.org/docs/JSONCompilationDatabase.html), where I see it is a json array. 

Here is the output from ` clink --debug --jobs 1  --parse-c=clang -i namefile.files >clink_outout.log 2>&1` , up until the first errors reported: [clink_outout.log.tar.gz](https://github.com/Smattr/clink/files/15318032/clink_outout.log.tar.gz)


If I can not use `compile_commands.json` (lets say because it is too large), maybe some alternatives can work:
 - the `compile_flags.txt` is a limited alternative, but it works for my real project (like I said, with 13000 source files), and is oficially supported and documented by clang (https://clang.llvm.org/docs/JSONCompilationDatabase.html)
 - also another option is to do what ycm-core plugin (for Vim) does: use a script file, with a method that is invoked for each source file, and the method returns compiler flags for building that source (see [.ycm_extra_conf.py](https://github.com/ycm-core/YouCompleteMe?tab=readme-ov-file#option-2-provide-the-flags-manually)

Thank you for the support and hopefully this can be fixed or worked-around. 
This is such a great tool by the way ! Just amazing ... !

**Comment by Smattr** [comment]
Interesting. Clink claims it can’t find some of these files in the compile_commands.json database, even though they’re clearly there. It’s been a while since I looked at this part of the code base, but I thought it was just interacting with the libclang API, which means libclang can’t find these entries for some reason. I’ll have to debug this a bit further locally… Thanks for attaching those files.

> This is such a great tool by the way ! Just amazing ... !

Thanks! Glad you like it :)

**Comment by terminatorul** [comment]
Is there a way in clang API to check for errors from parsing the compilation database ?

**Comment by Smattr** [comment]
Sorry it took a while to find time to investigate this one. The problem appears to be that the compilation database parsing code was simply too strict in what it would accept. Do you have time to see if the fix I posted in https://github.com/Smattr/clink/pull/248 works for you?

**Comment by Smattr** [comment]
It occurs to me just now that you also have relative `-I…` paths in your `arguments`. Not sure if this will cause problems as well, but lets see if this step gets us some progress first.

**Comment by Smattr** [comment]
I’ll merge the PR now and continue to refine that area going forwards. Let me know if there’s further things you need addressing here.
