### ISSUE TITLE
[Feature] Export code structures in 'Graphviz' format

### ISSUE THREAD

**Issue by pidgeon777** [Smattr/clink#50]
The following tool is used to visualize C/C++ function calls and callers, by making use of the `cscope` database:

https://sourceforge.net/projects/tceetree/

As a suggestion, `clink` tool could directly replace `tceetree` functionality, by exporting `Graphviz` textual descriptions to generate some useful graphs.

For example:

- Given a function, show a tree with callers and calls.
- Given a symbol, show a tree/table with the functions where it is defined/read/written.
- Graphical representation of pointer relationships (functions, structures...).

It should be quite easy to create some `Graphviz` textual description by elaborating your internal database, similarly to what `tceetree` does.

Example of code structure in `Graphviz` *DOT* format:

```dot
digraph ctree
{
	subgraph cluster_drv_cpu_c { label="drv_cpu.c"; labeljust="l"; write_src_in_ddr [color="red",fontcolor="red"]; }
	write_src_in_ddr->getpagesize [label="drv_cpu.c"];
	subgraph cluster_LIBRARY { label="LIBRARY"; labeljust="l"; getpagesize; }
	write_src_in_ddr->fopen [label="drv_cpu.c"];
	subgraph cluster_LIBRARY { label="LIBRARY"; labeljust="l"; fopen; }
	main->write_src_in_ddr [label="main.c"];
	subgraph cluster_main_c { label="main.c"; labeljust="l"; main; }
}
```

A good reference:

https://www.graphviz.org/pdf/dotguide.pdf

**Comment by Smattr** [comment]
I assume this was answered by the above.
